services:
  db:
    image: postgres
    container_name: my_post
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
  django:
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    build: 
      context: backend
    ports:
      - '8000:8000'
    depends_on:
      - db
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
volumes:
  pgdbdata:
