services:
  db:
    image: postgres
    container_name: my_post
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  web:
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/PycharmProjects/backend/
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
