# Generated by Django 5.0.6 on 2024-05-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_like_unique_together_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('author', 'subscriber')},
        ),
    ]
